// Minimal i18n: picks the table by Obsidian's UI language ("zh" / "zh-TW" → Chinese, anything else → English).
// t(key, vars) substitutes {name} placeholders. Console/log messages stay English on purpose.

const en: Record<string, string> = {
  // ribbon / commands
  RIBBON: "Local Images Plus",
  CMD_LOCALIZE_CURRENT_PLUGIN: "Localize attachments for the current note (plugin folder)",
  CMD_LOCALIZE_CURRENT_OBS: "Localize attachments for the current note (Obsidian folder)",
  CMD_TITLE_AS_NAME: "Set the first found # header as a note name.",
  CMD_LOCALIZE_ALL_PLUGIN: "Localize attachments for all your notes (plugin folder)",
  CMD_SELECTION_TO_URI: "Convert selection to URI",
  CMD_HTML_TO_MD: "Convert selection from html to markdown",
  CMD_ORPHANS_OBS: "Remove all orphaned attachments (Obsidian folder)",
  CMD_ORPHANS_PLUGIN: "Remove all orphaned attachments (Plugin folder)",

  // modal buttons
  CANCEL: "Cancel",
  CONFIRM: "Confirm",
  OK: "OK",

  // notices
  N_FOLDER_TRASHED: "Attachment folder {dir} was moved to trash can.",
  N_FOLDER_RENAMED: "Attachment folder was renamed to {dir}",
  N_FOLDER_MOVE_FAIL: "Cannot move attachment folder: \r\n{err}",
  N_NO_CURRENT_NOTE: "Cannot get current note! ",
  N_PROCESSED: "Attachments for \"{path}\" were processed.",
  N_PROCESSED_PARTIAL: "WARNING!\r\nAttachments for \"{path}\" were processed, but some attachments were not downloaded/replaced...",
  N_PROCESSED_NOCHANGE: "Page \"{path}\" has been processed, but nothing was changed.",
  N_SELECT_NOTE: "Please select a note or click inside selected note in canvas.",
  N_SELECT_NOTE2: "Please, select a note or click inside a note in canvas!",
  N_START_ALL: "\nStart processing. Total {count} pages. ",
  N_PROCESSING_PAGE: "\nProcessing \n\"{path}\" \nPage {index} of {count}",
  N_ALL_DONE: "\n{count} pages were processed.",
  N_LINKS_FOUND: "Media links were found, processing...",
  N_NEED_SETTINGS: "This command requires the settings 'Next to note in the folder specified below' and pattern '${notename}' at the end to be enabled, also the path cannot contain ${date} pattern.\nPlease, change settings first!\r\n",
  N_FOLDER_MISSING: "The attachment folder {dir} does not exist!",
  N_CONFIRM_ORPHANS: "Confirm remove {count} orphan(s) from '{dir}'\r\n\r\n      ",
  N_CONFIRM_ORPHANS_OBS: "Confirm remove {count} orphan(s) from '{dir}  '\r\n           NOTE: Be careful when running this command on Obsidian attachments folder, since some html-linked files may also be moved.\r\n      ",
  N_NO_ORPHANS: "No orphaned files found!",
  N_ROOT_FORBIDDEN: "This command cannot run on vault's root or on subfolder next to note!\nPlease, change settings first!\r\n",
  N_REMOVED_COMPLETELY: "{count} file(s) were deleted completely.",
  N_REMOVED_SYS_TRASH: "{count} file(s) were moved to the system garbage can.",
  N_REMOVED_OBS_TRASH: "{count} file(s) were moved to the Obsidian garbage can.",
  N_CONFIRM_ALL: "Confirm processing all pages.\r\n ",
  N_OBS_FOLDER_CREATED: "You obsidian media folder set to '{dir}', and has been created by the plugin. Please, try again. ",
  N_NOTE_ATT_PROCESSED: "{count} attachments for note {path} were processed.",
  N_RENAMED: "The note was renamed to {path}",
  N_RENAME_FAIL: "Cannot rename.",
  N_FILE_ERROR: "LocalImagesPlus: Error while handling file {name}, {err}",

  // settings: headings
  H_INTERFACE: "Interface settings",
  H_PROCESSING: "Processing settings",
  H_NOTE: "Note settings",
  H_ORPHANS: "Orphaned attachments",
  H_MEDIA_FOLDER: "Media folder settings",
  H_TROUBLESHOOTING: "Troubleshooting",

  // settings: items
  S_SHOW_NOTIF: "Show notifications",
  S_SHOW_NOTIF_D: "Show notifications when pages were processed.",
  S_DIS_ADD_COM: "Disable additional commands",
  S_DIS_ADD_COM_D: "Do not show additional commands in command palette. Reload the plugin in settings to take effect (turn off/on).",
  S_AUTO: "Automatic processing",
  S_AUTO_D: "Process notes on create/copy/paste.",
  S_AUTO_INTERVAL: "Automatic processing interval",
  S_AUTO_INTERVAL_D: "Interval in seconds for processing update. It takes some time to reveal changed content of a note to plugins.",
  E_INTERVAL_RANGE: "The value should be a positive integer number between 5 and 3600!",
  S_RETRIES: "Number of retries for every single attachment",
  S_RETRIES_D: "If an error occurs during downloading (network etc.) try to re-download several times.",
  E_RETRIES_RANGE: "The value should be a positive integer number between 1 and 6!",
  S_PROCESS_CREATED: "Process all new markdown files",
  S_PROCESS_CREATED_D: "Process all new created/cloud-synced files with corresponding extensions.",
  S_PROCESS_ALL: "Process all new attachments",
  S_PROCESS_ALL_D: "The plugin will also move all attachments from obsidian default folder to plugin folder.",
  S_MD5: "Use MD5 for new attachments (Pasted images and files)",
  S_MD5_D: "The plugin will use MD5 when renaming all new attachments.",
  S_DOWN_UNKNOWN: "Download unknown filetypes",
  S_DOWN_UNKNOWN_D: "Download unknown filetypes and save them with .unknown extension.",
  S_COMPRESS_WEB: "Compress images (Web Images)",
  S_COMPRESS_WEB_D: "Compress all downloaded images. May reduce file size by several times, but can also affect performance.",
  S_COMPRESS_PASTED: "Compress images (Pasted Images)",
  S_COMPRESS_PASTED_D: "Compress all pasted images. May reduce file size by several times, but can also affect performance.",
  S_COMPRESS_TYPE: "Compression type",
  S_COMPRESS_TYPE_D: "Select image compression type. Keep in mind that webp format has image size limitations.",
  S_EXCLUDED_FOLDERS: "Excluded folders",
  S_EXCLUDED_FOLDERS_D: "Excluded folders. New files in these folders will not be processed automatically.",
  S_EXCLUDED_FOLDERS_P: "Enter the full path in new lines, e.g. RootFolder/Subfolder.",
  S_QUALITY: "Image Quality",
  S_QUALITY_D: "Image quality selection (30 to 100).",
  E_QUALITY_RANGE: "The value should be a positive integer number between 10 and 100!",
  S_SIZE_LIMIT: "File size lower limit in Kb",
  S_SIZE_LIMIT_D: "Do not download files with size less than this value. Set 0 for no limit.",
  E_POSITIVE_INT: "The value should be a positive integer!",
  S_EXCLUSIONS: "Exclusions",
  S_EXCLUSIONS_D: "The plugin will not download attachments with these extensions.",
  S_NO_OBS_FOLDER: "Do not create Obsidian attachment folder (For compatibility with other plugins)",
  S_NO_OBS_FOLDER_D: "The plugin will not create an Obsidian attachments folder. This may cause the plugin to behave incorrectly. ",
  S_CAPTIONS: "Preserve link captions",
  S_CAPTIONS_D: "Add media links captions to converted tags.",
  S_ADD_NAME: "Add original filename or 'Open file' tag",
  S_ADD_NAME_D: "Add [[original filename]] or [original filename](link to attachment) after replaced tag (only for file:// protocol or dropped/pasted files ).",
  S_INCLUDE: "Include pattern",
  S_INCLUDE_D: "Include only files with extensions only matching this pattern. Example: md|canvas",
  E_UNSAFE_REGEX: "Unsafe regex! https://www.npmjs.com/package/safe-regex",
  S_REMOVE_COMPLETELY: "Remove files completely",
  S_REMOVE_COMPLETELY_D: "Do not move orphaned files into the garbage can.",
  S_PATH_IN_TAGS: "How to write paths in tags",
  S_PATH_IN_TAGS_D: "Select whether to write full paths in tags or not.",
  O_FULL_PATH: "Full path",
  O_RELATIVE: "Relative to note",
  O_FILENAME: "Only filename",
  S_DATE_FORMAT: "Date format",
  S_DATE_FORMAT_D: "Date format for ${date} variable. E.g. | MMMM Do YYYY, h:mm:ss a (March 20th 2024, 10:54:46 am) | dddd  (Wednesday) | MMM Do YY  (Mar 20th 24)",
  E_UNSAFE_FOLDER: "Unsafe folder name! Some chars are forbidden in some filesystems.",
  S_SAVE_WHERE: "Folder to save new attachments",
  S_SAVE_WHERE_D: "Select where all new attachments will be saved.\nYou can use templates e.g. _resouces/${date}/${notename}",
  O_OBS_SETTINGS: "Copy Obsidian settings",
  O_ROOT_BELOW: "In the root folder specified below",
  O_NEXT_TO_NOTE: "Next to note in the folder specified below",
  S_MOVE_FOLDER: "Move/delete/rename media folder",
  S_MOVE_FOLDER_D: "Rename or move this folder to the obsidian or system garbage can when the associated note is deleted/renamed/moved. This setting takes effect only if the path contains ${notename} template at the end and the options 'Next to note in the folder specified below' / 'Relative to note' are selected. Use this setting at your own risk.",
  S_MEDIA_FOLDER: "Media folder",
  S_MEDIA_FOLDER_D: "Folder to keep all downloaded media files.",
  S_DEBUG: "Debug",
  S_DEBUG_D: "Enable debug output to console.",
}

const zh: Record<string, string> = {
  RIBBON: "Local Images Plus",
  CMD_LOCALIZE_CURRENT_PLUGIN: "本地化当前笔记的附件（插件文件夹）",
  CMD_LOCALIZE_CURRENT_OBS: "本地化当前笔记的附件（Obsidian 文件夹）",
  CMD_TITLE_AS_NAME: "把第一个 # 标题设为笔记文件名",
  CMD_LOCALIZE_ALL_PLUGIN: "本地化所有笔记的附件（插件文件夹）",
  CMD_SELECTION_TO_URI: "把选中内容转成 URI",
  CMD_HTML_TO_MD: "把选中的 HTML 转成 Markdown",
  CMD_ORPHANS_OBS: "清理所有孤立附件（Obsidian 文件夹）",
  CMD_ORPHANS_PLUGIN: "清理所有孤立附件（插件文件夹）",

  CANCEL: "取消",
  CONFIRM: "确认",
  OK: "好",

  N_FOLDER_TRASHED: "附件文件夹 {dir} 已移到回收站。",
  N_FOLDER_RENAMED: "附件文件夹已改名为 {dir}",
  N_FOLDER_MOVE_FAIL: "无法移动附件文件夹：\r\n{err}",
  N_NO_CURRENT_NOTE: "找不到当前笔记！",
  N_PROCESSED: "「{path}」的附件已处理完成。",
  N_PROCESSED_PARTIAL: "注意！\r\n「{path}」的附件已处理，但有部分附件没能下载或替换……",
  N_PROCESSED_NOCHANGE: "「{path}」已处理，没有需要改动的内容。",
  N_SELECT_NOTE: "请先选中一篇笔记，或在白板里点进要处理的笔记。",
  N_SELECT_NOTE2: "请先选中一篇笔记，或在白板里点进一篇笔记！",
  N_START_ALL: "\n开始处理，共 {count} 篇。",
  N_PROCESSING_PAGE: "\n正在处理\n「{path}」\n第 {index} / {count} 篇",
  N_ALL_DONE: "\n已处理 {count} 篇笔记。",
  N_LINKS_FOUND: "发现媒体链接，正在处理……",
  N_NEED_SETTINGS: "这条命令要求：附件保存位置选「笔记旁边的指定文件夹」，路径以 ${notename} 结尾，且不能含 ${date}。\n请先修改设置！\r\n",
  N_FOLDER_MISSING: "附件文件夹 {dir} 不存在！",
  N_CONFIRM_ORPHANS: "确认从「{dir}」删除 {count} 个孤立附件？\r\n\r\n      ",
  N_CONFIRM_ORPHANS_OBS: "确认从「{dir}」删除 {count} 个孤立附件？\r\n           注意：对 Obsidian 附件文件夹执行此命令要小心，某些以 HTML 方式引用的文件也可能被一并移走。\r\n      ",
  N_NO_ORPHANS: "没有发现孤立附件。",
  N_ROOT_FORBIDDEN: "这条命令不能在库根目录或笔记旁的子文件夹上运行！\n请先修改设置！\r\n",
  N_REMOVED_COMPLETELY: "已彻底删除 {count} 个文件。",
  N_REMOVED_SYS_TRASH: "已把 {count} 个文件移到系统回收站。",
  N_REMOVED_OBS_TRASH: "已把 {count} 个文件移到 Obsidian 回收站。",
  N_CONFIRM_ALL: "确认处理所有笔记？\r\n ",
  N_OBS_FOLDER_CREATED: "你的 Obsidian 附件文件夹设为「{dir}」，插件刚刚为你创建了它，请再试一次。",
  N_NOTE_ATT_PROCESSED: "笔记 {path} 的 {count} 个附件已处理。",
  N_RENAMED: "笔记已改名为 {path}",
  N_RENAME_FAIL: "无法改名。",
  N_FILE_ERROR: "LocalImagesPlus：处理文件 {name} 时出错，{err}",

  H_INTERFACE: "界面",
  H_PROCESSING: "处理",
  H_NOTE: "笔记",
  H_ORPHANS: "孤立附件",
  H_MEDIA_FOLDER: "媒体文件夹",
  H_TROUBLESHOOTING: "排查问题",

  S_SHOW_NOTIF: "显示通知",
  S_SHOW_NOTIF_D: "笔记处理完成后弹出通知。",
  S_DIS_ADD_COM: "停用附加命令",
  S_DIS_ADD_COM_D: "不在命令面板里显示附加命令。需要在设置里关掉再打开插件才生效。",
  S_AUTO: "自动处理",
  S_AUTO_D: "新建 / 复制 / 粘贴时自动处理笔记。",
  S_AUTO_INTERVAL: "自动处理间隔",
  S_AUTO_INTERVAL_D: "检查间隔（秒）。笔记内容的改动需要一点时间才能被插件看到。",
  E_INTERVAL_RANGE: "必须是 5 到 3600 之间的整数！",
  S_RETRIES: "每个附件的重试次数",
  S_RETRIES_D: "下载出错（网络等原因）时重试几次。",
  E_RETRIES_RANGE: "必须是 1 到 6 之间的整数！",
  S_PROCESS_CREATED: "处理所有新的 Markdown 文件",
  S_PROCESS_CREATED_D: "新建或从云端同步下来的、扩展名匹配的文件都会被处理。",
  S_PROCESS_ALL: "处理所有新附件",
  S_PROCESS_ALL_D: "插件还会把 Obsidian 默认文件夹里的附件都移到插件文件夹。",
  S_MD5: "新附件用 MD5 命名（粘贴的图片和文件）",
  S_MD5_D: "给新附件改名时使用 MD5 值。",
  S_DOWN_UNKNOWN: "下载未知类型的文件",
  S_DOWN_UNKNOWN_D: "未知类型的文件也下载，保存为 .unknown 扩展名。",
  S_COMPRESS_WEB: "压缩图片（网络图片）",
  S_COMPRESS_WEB_D: "压缩所有下载的图片。体积可能缩小好几倍，但会影响性能。",
  S_COMPRESS_PASTED: "压缩图片（粘贴的图片）",
  S_COMPRESS_PASTED_D: "压缩所有粘贴的图片。体积可能缩小好几倍，但会影响性能。",
  S_COMPRESS_TYPE: "压缩格式",
  S_COMPRESS_TYPE_D: "选择图片压缩格式。注意 WebP 对图片尺寸有上限。",
  S_EXCLUDED_FOLDERS: "排除的文件夹",
  S_EXCLUDED_FOLDERS_D: "这些文件夹里的新文件不会被自动处理。",
  S_EXCLUDED_FOLDERS_P: "每行一个完整路径，例如 RootFolder/Subfolder。",
  S_QUALITY: "图片质量",
  S_QUALITY_D: "图片质量（30 到 100）。",
  E_QUALITY_RANGE: "必须是 10 到 100 之间的整数！",
  S_SIZE_LIMIT: "文件大小下限（KB）",
  S_SIZE_LIMIT_D: "小于这个大小的文件不下载。0 = 不限制。",
  E_POSITIVE_INT: "必须是正整数！",
  S_EXCLUSIONS: "排除的扩展名",
  S_EXCLUSIONS_D: "这些扩展名的附件不下载。",
  S_NO_OBS_FOLDER: "不创建 Obsidian 附件文件夹（为兼容其他插件）",
  S_NO_OBS_FOLDER_D: "插件不再创建 Obsidian 附件文件夹。这可能导致插件工作不正常。",
  S_CAPTIONS: "保留链接说明文字",
  S_CAPTIONS_D: "把媒体链接的说明文字带进转换后的标签里。",
  S_ADD_NAME: "附加原始文件名或「打开文件」标签",
  S_ADD_NAME_D: "在替换后的标签后面加上 [[原始文件名]] 或 [原始文件名](附件链接)（仅对 file:// 协议或拖入 / 粘贴的文件有效）。",
  S_INCLUDE: "包含规则",
  S_INCLUDE_D: "只处理扩展名匹配这个规则的文件。例如：md|canvas",
  E_UNSAFE_REGEX: "不安全的正则表达式！https://www.npmjs.com/package/safe-regex",
  S_REMOVE_COMPLETELY: "彻底删除文件",
  S_REMOVE_COMPLETELY_D: "孤立附件直接删除，不放进回收站。",
  S_PATH_IN_TAGS: "标签里的路径写法",
  S_PATH_IN_TAGS_D: "选择标签里是否写完整路径。",
  O_FULL_PATH: "完整路径",
  O_RELATIVE: "相对笔记的路径",
  O_FILENAME: "只写文件名",
  S_DATE_FORMAT: "日期格式",
  S_DATE_FORMAT_D: "${date} 变量的格式。例如 | MMMM Do YYYY, h:mm:ss a（March 20th 2024, 10:54:46 am）| dddd（Wednesday）| MMM Do YY（Mar 20th 24）",
  E_UNSAFE_FOLDER: "文件夹名不安全！有些字符在某些文件系统里不允许使用。",
  S_SAVE_WHERE: "新附件保存到哪里",
  S_SAVE_WHERE_D: "选择新附件的保存位置。\n可以用模板，例如 _resouces/${date}/${notename}",
  O_OBS_SETTINGS: "跟随 Obsidian 设置",
  O_ROOT_BELOW: "下面指定的根文件夹",
  O_NEXT_TO_NOTE: "笔记旁边的指定文件夹",
  S_MOVE_FOLDER: "随笔记移动 / 删除 / 改名媒体文件夹",
  S_MOVE_FOLDER_D: "关联的笔记被删除 / 改名 / 移动时，把这个文件夹一起改名或移到 Obsidian / 系统回收站。只有路径以 ${notename} 结尾、并且选了「笔记旁边的指定文件夹」/「相对笔记的路径」时才生效。风险自负。",
  S_MEDIA_FOLDER: "媒体文件夹",
  S_MEDIA_FOLDER_D: "存放所有下载的媒体文件的文件夹。",
  S_DEBUG: "调试",
  S_DEBUG_D: "把调试信息输出到控制台。",
}

const pickTable = () => {
  let lang = ""
  try { lang = String(window.localStorage.getItem("language") || "") } catch { /* ignore */ }
  return lang.toLowerCase().startsWith("zh") ? zh : en
}

export function t(key: string, vars?: Record<string, string | number>): string {
  let s = pickTable()[key] ?? en[key] ?? key
  if (vars) {
    for (const k of Object.keys(vars)) {
      s = s.split("{" + k + "}").join(String(vars[k]))
    }
  }
  return s
}
